version: '3.8'
services:
  jenkins:
    build:
      context: ./jenkins_config
      dockerfile: Dockerfile
    container_name: jenkins-auth-min
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /Users/pedroalves/.docker/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/usr/share/jenkins/ref/jenkins.yaml
    networks:
      - jenkins-network

volumes:
  jenkins_home:
    driver: local

networks:
  jenkins-network:
    driver: bridge
